[worker_nodeN]
3.14.149.168 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
3.148.105.201 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
18.218.209.34 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
3.143.213.161 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
3.17.28.140 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[ha-proxy]
18.117.9.116 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-master1]
3.148.105.201 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-master2]
3.14.149.168 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-worker1]
18.218.209.34 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-worker2]
3.143.213.161 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-worker3]
3.17.28.140 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa


; [cluster-entry-point] 
; 44.206.245.239 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa


