[worker_nodeN]
54.162.12.133 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
34.201.45.227 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
54.164.31.87 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
174.129.78.183 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
34.238.42.118 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa


[ha-proxy]
184.72.98.235 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-master1]
54.164.31.87 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-master2]
34.201.45.227 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-worker1]
174.129.78.183 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-worker2]
54.162.12.133 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube-worker3]
34.238.42.118 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa


; [cluster-entry-point] 
; 44.206.245.239 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa