---
- hosts: worker_nodeN
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - gnupg-agent
      - software-properties-common

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
      state: present

  - name: Install containerd
    vars:
      containerd_version: "1.6.4-1"
    apt:
      name: containerd.io={{ containerd_version }}
      state: present 

  - name: Configure containerd
    copy:
      src: files/config.toml
      dest: /etc/containerd/config.toml
      mode: '0644'

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0


  - name: Create directory for Kubernetes apt key
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'
      owner: root
      group: root 

  - name: Download the Kubernetes apt key
    shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Add Kubernetes apt repository
    copy:
      dest: /etc/apt/sources.list.d/kubernetes.list
      content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
      mode: '0644'
      owner: root
      group: root

  - name: Update the apt package index again
    apt:
      update_cache: yes

  - name: Install Kubernetes binaries
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet=1.28.9-2.1
        - kubeadm=1.28.9-2.1
        - kubectl=1.28.9-2.1
    

  - name: Stop kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: stopped

  - name: Load overlay module
    modprobe:
      name: overlay
      state: present

  - name: Load br_netfilter module
    modprobe:
      name: br_netfilter
      state: present

  - name: Persist modules
    copy:
      content: |
        overlay
        br_netfilter
      dest: /etc/modules-load.d/k8s.conf

  - name: Set sysctl params
    copy:
      content: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
      dest: /etc/sysctl.d/k8s.conf

  - name: Load sysctl settings
    shell: |
      sysctl --system
